# Site settings
title : JavaChen's Blog
tagline: Sharing Technology, Recording Life
keywords : java, hadoop, hive, hbase, mapreduce, nosql, solr, solrcloud, linux, python, lua, postgresql, mysql
description: 关注开源、Java、Hadoop、NoSql、Pentaho以及数据可视化
baseurl: ""
url: "//blog.javachen.com"
highlighter: pygments
paginate: 12
author:
    name: JavaChen
    github: javachen
    email: june.chan(a)foxmail.com
    gitcafe: javachen
    twitter:
    facebook:
    googleplus:
    weibo: chenzhijun
qiniudn: //javachen.qiniudn.com
atom_path: /atom.xml
rss_path: /rss.xml

# Build settings
markdown: redcarpet
redcarpet:
  extensions: [ "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify"]
permalink: /:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]


# comment
comments:
  duoshuo:
    name: javachen
    rcomments:
        num: 10
        avatar: 0
        time: 0
        title: 0
        admin: 0
        length: 12
# 网站统计
analytics:
    baidu:
        siteid:         # 百度统计 js 代码后的字符串
    51la:
        uid: 12111481
# blogroll
blogroll : true
brlist :
    - text : JavaChen Blog
      url : //blog.javachen.com/
    - text : JavaChen Sitemap
      url : /sitemap.xml
    - text : 圆木菠萝罐
      url : //blog.boluotou.com/
    - text : Log4D
      url : //log4d.com/
    - text : A Java geek
      url : //blog.frankel.ch
    - text : Kohsuke Kawaguchi
      url : //kohsuke.org/
    - text : 并行实验室
      url : //www.parallellabs.com/
    - text : 灵魂机器
      url : //cn.soulmachine.me/
    - text : MayCoder
      url : //code6.github.io/
    - text : 刘兰涛的Blog
      url : //blog.liulantao.com/
    - text : zJun Blog
      url : //zjun.github.io/
