# For more see: http://jekyllrb.com/docs/permalinks
permalink: /:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
paginate: 10

markdown: redcarpet
redcarpet:
  extensions: [ "fenced_code_blocks", "autolink", "tables", "strikethrough", "superscript", "with_toc_data", "highlight", "prettify"]

title : JavaChen Blog
tagline: Site Tagline
keywords : java,hadoop,hive,hbase,mapreduce,impala,nosql,solr,solrcloud,linux,python,lua,postgresql,mysql
description: 关注开源、Java、Hadoop、Pentaho、NoSql以及数据可视化
version : 0.12
author :
  name : JavaChen
  email : june.chan(a)foxmail.com
  github : javachen
  twitter : 
  feedburner : 
  weibo : chenzhijun

production_url : http://blog.javachen.com

JB :
  version : 0.3.0
  BASE_PATH : false
  ASSET_PATH : false
  archive_path: /archive.html
  categories_path : /categories.html
  tags_path : /tags.html
  atom_path : /atom.xml
  rss_path : /rss.xml

  comments :
    provider : duoshuo
    disqus :
      short_name :
    livefyre :
      site_id :
    intensedebate :
      account :
    facebook :
      appid :
      num_posts:
      width: 580
      colorscheme: light
    duoshuo :
      name : javachen
      comments :
        num: 5
        avatar : 0
        time: 0
        title : 0
        admin : 0
        length : 14
      visitors :
        num : 15

  analytics :
    provider : custom
    google :
        tracking_id :
    getclicky :
      site_id :
    mixpanel :
        token : '_MIXPANEL_TOKEN_'
    piwik :
        baseURL : 'myserver.tld/piwik' # Piwik installation address (without protocol)
        idsite : '1'                   # the id of the site on Piwik
    51la :
        uid : '12111481'
       
  sharing :
    provider : false
    
  posts_collate :
    provider : "custom"

  tags_list :
    provider : "custom"

  # Settings for all other include helpers can be defined by creating 
  # a hash with key named for the given helper. ex:
  #
  #   pages_list :
  #     provider : "custom"
  #
  # Setting any helper's provider to 'custom' will bypass the helper code
  # and include your custom code. Your custom file must be defined at:
  #   ./_includes/custom/[HELPER]
  # where [HELPER] is the name of the helper you are overriding.

  blogroll : true
  brlist :
    - text : JavaChen Blog
      url : //blog.javachen.com/
    - text : JavaChen Sitemap
      url : /sitemap.xml
    - text : 圆木菠萝罐
      url : //blog.boluotou.com/
    - text : Log4D
      url : //log4d.com/
    - text : A Java geek
      url : //blog.frankel.ch
    - text : Kohsuke Kawaguchi
      url : //kohsuke.org/
    - text : 并行实验室
      url : //www.parallellabs.com/
    - text : 灵魂机器
      url : //cn.soulmachine.me/
    - text : MayCoder
      url : //code6.github.io/
    - text : 刘兰涛的Blog
      url : //blog.liulantao.com/
    - text : zJun Blog
      url : //zjun.github.io/
